@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources Manager" as ADM
participant ":CreateJobUI" as UI
participant ":CreateJobController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "jobrepository\n:JobRepository" as JR
participant "job\n:Job" as TRABALHO

activate ADM

        ADM -> UI : asks to create a new job

        activate UI

'            UI --> ADM : requests data (name)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : getJobRepository()

            activate CTRL

            CTRL -> RepositorySingleton : getInstance()
                            activate RepositorySingleton

                                RepositorySingleton --> CTRL: repositories
                            deactivate RepositorySingleton

                 CTRL -> PLAT : getJobRepository()
                         activate PLAT

                     PLAT -> CTRL : jobRepository
                     deactivate PLAT
    deactivate CTRL
    UI --> ADM : requests name
    deactivate UI

    ADM -> UI : types requested name
    activate UI

            UI --> ADM : shows typed name and asks for confirmation
        deactivate UI

        ADM -> UI : confirms data
        activate UI

        UI -> CTRL : createJob(jobname)
        activate CTRL

            |||
            CTRL -> CTRL : getHRMFromSession()
            activate CTRL

                ref over CTRL
                Get HRM
                end

                CTRL --> CTRL : hrm
            deactivate CTRL

            |||
            CTRL -> JR: createJob(jobname)
            activate JR

                ref over JR
                Create Job
                end


                JR --> CTRL : job

            deactivate JR

            CTRL --> UI: job
            deactivate CTRL
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml