@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Human Resources Manager" as  HRM
participant ":System" as System

activate  HRM

     HRM -> System : asks to register a collaborator with a job and fundamental characteristics
    activate System

        System -->  HRM : requests collaborator data (name, birthdate, admission date, address, \ncontact info (mobile and email), taxpayer number, ID doc type and respective number)
    deactivate System

     HRM -> System : types requested data
    activate System

        System -->  HRM : shows job list and asks to select one
    deactivate System

     HRM -> System : selects a job
    activate System

        System -->  HRM : shows all data and requests confirmation
    deactivate System

     HRM -> System : confirms data
    activate System

        System -->  HRM : displays operation success
    deactivate System

@enduml