@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Green Spaces Manager" as GSM
participant ":System" as System

activate GSM

    GSM -> System : asks to add a new entry to the To-Do List
    activate System

        System --> GSM : shows list of green spaces and asks to select one
    deactivate System

    GSM -> System : selects green space
    activate System

    System --> GSM : requests entry data (title, task description, degree of urgency \n(this one is selectable), approximate duration)
    deactivate System

    GSM -> System : types/selects data
    activate System

    System --> GSM : shows data and requests confirmation
    deactivate System

    GSM -> System : confirms data
    activate System

    System --> GSM : displays operation success
    deactivate System

@enduml