@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Vehicle Fleet Manager" as ADM
participant ":ProduceMaintenanceListUI" as UI
participant ":ProduceMaintenanceListController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehicleRepository:\nVehicleRepository" as VR
participant "Vehicle" as VEICULO

activate ADM

        ADM -> UI : asks to list the vehicles that need maintenance

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : getVehicleRepository()
            activate CTRL

                CTRL -> PLAT : getVehicleRepository()
                activate PLAT

                    PLAT --> CTRL: vehicleRepository
                deactivate PLAT
                deactivate CTRL

                UI -> CTRL : getVehicles()
                        activate CTRL

                            CTRL -> PLAT : getVehicles()
                            activate PLAT

                                PLAT --> CTRL: vehicles
                            deactivate PLAT
                            deactivate CTRL





        UI -> CTRL : produceMaintenanecList()
        activate CTRL

            |||
            CTRL -> CTRL : getVFMFromSession()
            activate CTRL

ref over CTRL
Get VFM
end

                CTRL --> CTRL : vfm
            deactivate CTRL

            CTRL -> VR :  produceMaintenanecList()
                                 activate VR

            |||
            ref over VR
            Get Vehicle Parts
            end

ref over VR
Create List
end
                VR --> CTRL : maintenanceList

            deactivate VR

            CTRL --> UI : maintenanceList

            UI --> ADM: displays maintenance list
    deactivate UI

deactivate ADM

@enduml