@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "vehicleRepository:\nVehicleRepository" as VR
            loop for each maintenance data
            activate VR
            VR -> VR:                maintenanceList.add(maintenanceData);
end
                <-- VR : maintenanceList

            deactivate VR


@enduml