@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class Job {
    - name: String
}

class JobManager {
    + createJob(name: String): boolean
}

class HRManager {
    + manageSkills(): void
}

JobManager --> Job: Manages
HRManager --> JobManager: Uses


Repositories -> Repositories : instance
ApplicationSession -> ApplicationSession : instance

CreateJobUI .> CreateJobController

CreateJobController .> Repositories : repositories

Repositories --> "1" OrganizationRepository

OrganizationRepository --> "*" Organization
ApplicationSession --> "1" UserSession : userSession

CreateJobController ..> "1" Organization : organization
CreateJobController ..> ApplicationSession
CreateJobController ..> UserSession
Organization "1" --> "*" Job : attributes
Job --> HRManager : createdBy

Organization --> "*" HRManager : employs

@enduml