@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "organization\n:Organization" as ORG
participant "job\n:Job" as TAREFA
participant "jobrepository\n:JobRepository" as JR

autonumber 16
-> ORG: createJob(jobname)

autonumber 16.1
activate ORG
    group Create Job


        activate ORG

                        ORG -> TAREFA**: create(jobname, hrm)
                        ORG -> ORG: validateJob(job)
                        ORG -> JR: addJob(job)

        deactivate ORG

 <-ORG: job


@enduml