@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Fleet Manager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to list the vehicles that need check-up
    activate System

        System --> Employee : goes through all vehicles with registered check-up dates\nselects those that have e already exceeded the number of km required for the inspection\n creates a list with said vehicles and shows it
    deactivate System

@enduml