@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class Collaborator {
    name
    birthdate
    admission date
    address
    contact info (mobile and email)
    taxpayer number
    ID doc type and number
}

class Task {
    title
    description
    status
    startDate
    duration
    associatedTeam
}

class TeamRepository {
    teams
}

class TaskRepository {
    tasks
}

class Team {
    collaborators
    teamID
}

'class User {
'    name
'    email
'    password
'}

Team "1" -- "*" Collaborator: consists of >
Team "1" - "1" TeamRepository: stored in >
Collaborator "1" - "1" Task: records completion of >
Task "1" - "1" TaskRepository: stored in >
Team "1" - "*" Task: assigned to >
@endumli