
@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Vehicle and Equipment\nFleet Manager" as VFM
participant ":RegisterMaintenanceUI" as UI
participant ":RegisterMaintenanceController" as CTRL
participant ":Repositories" as RepositorySingleton
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehicleRepository\n:VehicleRepository" as VR
participant "Vehicle" as VEICULO

activate VFM

        VFM -> UI : asks to register a vehicle's maintenance date

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create
            activate CTRL

                        CTRL -> RepositorySingleton : getInstance()
                                        activate RepositorySingleton

                                            RepositorySingleton --> CTRL: repositories
                                        deactivate RepositorySingleton

                             CTRL -> PLAT : getVehicleRepository()
                                     activate PLAT

                                 PLAT --> CTRL : vehicleRepository
                                 deactivate PLAT

                                 CTRL --> UI : vehicleRepository
                                 deactivate CTRL

               UI -> CTRL : getVehicles()
               activate CTRL

                       CTRL -> VR : getVehicles()
                               activate VR

                           VR --> CTRL : vehicles
                           deactivate VR

                           CTRL --> UI : vehicles
                           deactivate CTRL


            UI --> VFM : shows list of vehicles (by their plate number) and asks to select one.
        deactivate UI

    VFM -> UI : selects vehicle
    activate UI

                   UI -> VR : getPlateNumber()
                   activate VR

                               VR --> UI : vehiclePlateNumber
                               deactivate VR

    UI --> VFM : requests data (current Km and maintenance date)
    deactivate UI
    
    VFM -> UI : types data
    activate UI

        UI --> VFM : shows all data and requests confirmation
    deactivate UI

    VFM -> UI : confirms data
    activate UI

        UI -> CTRL : registerMaintenace(plate ID, brand, model, type, \ncurrent KMs and date of maintenance)
        activate CTRL

                CTRL -> CTRL : getVFMFromSession()
                            activate CTRL

                ref over CTRL
                Get VFM
                end

                                CTRL --> CTRL : VFM
                          deactivate CTRL

            |||
            CTRL -> VR: registerMaintenance(plateID, currentKm, maintenanceDate)
            activate VR

                VR -> VEICULO: setLastMaintenanceDate(maintenanceDate)
                activate VEICULO
                VR -> VEICULO: setCurrentKm(currentKm)
                deactivate VEICULO

            UI --> VFM: displays operation success
    deactivate UI

deactivate VFM

@enduml