@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "VehicleRepository" as VR
participant "Vehicle" as VEICULO

    group Register Maintenance Date

         -> VR: registerMaintenance(plateID, currentKm, maintenanceDate)
            activate VR

                VR -> VEICULO: setLastMaintenanceDate(maintenanceDate)
                activate VEICULO
                VR -> VEICULO: setCurrentKm(currentKm)
                deactivate VEICULO


@enduml