@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":RegisterMaintenanceController" as CTRL
participant ":Repositories" as RepositorySingleton
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehicleRepository\n:VehicleRepository" as VR
            activate CTRL

                        CTRL -> RepositorySingleton : getInstance()
                                        activate RepositorySingleton

                                            RepositorySingleton --> CTRL: repositories
                                        deactivate RepositorySingleton

                             CTRL -> PLAT : getVehicleRepository()
                                     activate PLAT

                                 PLAT --> CTRL : vehicleRepository
                                 deactivate PLAT

                                 <-- CTRL : vehicleRepository
                                 deactivate CTRL

               -> CTRL : getVehicles()
               activate CTRL

                       CTRL -> VR : getVehicles()
                               activate VR

                           VR --> CTRL : vehicles
                           deactivate VR

                           <-- CTRL : vehicles
                           deactivate CTRL



@enduml