@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



participant ":ConsultTasksController" as CTRL
participant "taskRepository:\nTaskRepository" as TAR
participant "ListMapper" as LM
participant "taskList" as TL
participant "taskListDTO" as TLDTO
participant "taskDTO" as TDTO

        -> CTRL : getTasksForCollaborator(Team team, LocalDate firstDate, LocalDate secondDate, String status)
                  activate CTRL
    group Get Tasks for Collaborator


                     loop for each task
                         CTRL -> TAR : getTaskByTeam(Team team)
                         activate TAR
                     end

                     TAR -> TL**: create()

                     TAR --> CTRL: taskList
                     deactivate TAR

                     CTRL -> LM: toDTO(taskList)
                     activate LM

                     LM -> TLDTO**: create()

                     loop for each task in taskList

                     LM -> TL: get(i)

                     LM -> LM: taskDTO = toDTO(task)
                     activate LM

                     LM --> TDTO**: create(task)
                     deactivate LM

                     LM -> TLDTO: add(taskDTO)
                     end



                     |||

                         LM --> CTRL : taskListDTO
                         deactivate LM


    end

    <-- CTRL : taskListDTO
deactivate CTRL


@enduml