@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Collaborator" as ADM
participant ":ConsultTasksUI" as UI
participant ":ConsultTasksController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "teamRepository:\nTeamRepository" as TER


activate ADM

        ADM -> UI : asks to consult the tasks assigned to them between two dates.

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create
            activate CTRL

                                  CTRL -> RepositorySingleton : getInstance()
                                                    activate RepositorySingleton

                                                        RepositorySingleton --> CTRL: repositories
                                                    deactivate RepositorySingleton

                                                     CTRL -> CTRL : getCollaboratorFromSession()
                                                     activate CTRL

                                                     ref over CTRL
                                                     Get Collaborator
                                                     end

                                                         CTRL --> CTRL : collaborator
                                                     deactivate CTRL

                                                     CTRL --> UI : collaborator
                                                     deactivate CTRL

            UI -> CTRL : getTeamRepository()
            activate CTRL

                CTRL -> PLAT : getTeamRepository()
                activate PLAT

           PLAT --> CTRL : teamRepository
           deactivate PLAT

           CTRL --> UI : teamRepository
           deactivate CTRL

                       UI -> CTRL : getTaskRepository()
                       activate CTRL

                           CTRL -> PLAT : getTaskRepository()
                           activate PLAT

                      PLAT --> CTRL : taskRepository
                      deactivate PLAT

                      CTRL --> UI : taskRepository
                      deactivate CTRL

        UI --> ADM: requests dates
        deactivate UI

        ADM -> UI: types dates
        activate UI

                UI --> ADM: asks if it would like to filter the tasks by status
                deactivate UI

                ADM -> UI: either accepts or declines (in case of acceptance, selects status)
                activate UI






        UI -> CTRL : getCollaboratorTeam(Collaborator collaborator)
        activate CTRL

        CTRL -> TER : getTeamByCollaborator(Collaborator collaborator)
        activate TER

        TER --> CTRL : team
        deactivate TER

        CTRL --> UI : team
        deactivate CTRL
        UI -> CTRL : getTasksForCollaborator(Team team, LocalDate firstDate, LocalDate secondDate, String status)
         activate CTRL
            ref over CTRL
            Get Tasks for Collaborator
            end
            CTRL --> UI : taskListDTO

            UI --> ADM: shows tasks assigned to the collaborator
    deactivate UI

deactivate ADM

@enduml