@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "vehicleRepository\n:VehicleRepository" as VR
participant "vehicle\n:Vehicle" as Vehicle

-> VR: addVehicle(vehicleModel,vehicleBrand,vehicleType, vehicleTareWeight, vehicleGrossWeight, vehicleCurrentKm, vehicleRegisterDate, vehicleAcquisitionDate, vehicleMaintenanceFrequencyKm, vehiclePlateNumber, vehicleLastMaintenanceDate, vfm)

activate VR
    group Create Vehicle

        VR -> Vehicle**: createVehicle(vehicleModel,vehicleBrand,vehicleType, vehicleTareWeight, vehicleGrossWeight, vehicleCurrentKm, \nvehicleRegisterDate, vehicleAcquisitionDate, vehicleMaintenanceFrequencyKm, vehiclePlateNumber, vehicleLastMaintenanceDate)
                activate VR
                    VR -> VR: validateVehicle(vehicle)
        VR -> VR: addVehicle(vehicle)


            deactivate VR

    end

    <-- VR : vehicle
deactivate VR


@enduml