@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Vehicle and Equipment Fleet Maneger" as ADM
participant ":AddVehicleUI" as UI
participant ":AddVehicleController" as CTRL
participant ":Repositories" as RepositorySingleton
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehicleRepository\n:VehicleRepository" as VR
participant "vehicle\n:Vehicle" as VEICULO

activate ADM

        ADM -> UI : asks to register a vehicle

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create
            activate CTRL

                        CTRL -> RepositorySingleton : getInstance()
                                        activate RepositorySingleton

                                            RepositorySingleton --> CTRL: repositories
                                        deactivate RepositorySingleton

                             CTRL -> PLAT : getVehicleRepository()
                                     activate PLAT

                                 PLAT -> CTRL : vehicleRepository
                                 deactivate PLAT
                                 deactivate CTRL

            UI --> ADM : requests data (Brand, Model, Type, Tare, Gross Weight, Current Km, \nRegister Date, Acquisition Date, Maintenance/Check-up Frequency, Plate Number, Last Maintenance Date)
        deactivate UI

    ADM -> UI : types requested data
    activate UI

        UI --> ADM : shows all data and requests confirmation
    deactivate UI

    ADM -> UI : confirms data
    activate UI

        UI -> CTRL : addVehicle(vehicleModel,vehicleBrand,vehicleType, vehicleTareWeight, vehicleGrossWeight, vehicleCurrentKm, vehicleRegisterDate, vehicleAcquisitionDate, vehicleMaintenanceFrequencyKm, vehiclePlateNumber, vehicleLastMaintenanceDate)
        activate CTRL


            |||
            CTRL -> CTRL : getVFMFromSession()
            activate CTRL

            ref over CTRL
            Get VFM
            end

                CTRL --> CTRL : vfm
            deactivate CTRL

            |||
            CTRL -> VR: addVehicle(vehicleModel,vehicleBrand,vehicleType, vehicleTareWeight, vehicleGrossWeight, vehicleCurrentKm, vehicleRegisterDate, vehicleAcquisitionDate, vehicleMaintenanceFrequencyKm, vehiclePlateNumber, vehicleLastMaintenanceDate)
            activate VR

                ref over VR
                Create Vehicle
                end

                VR --> CTRL : vehicle

            deactivate VR

            CTRL --> UI: vehicle
            deactivate CTRL
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml