@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US02 Alternative One

autonumber

actor "Human Resources Manager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to assign a skill to a collaborator
    activate System

        System --> Employee : shows a list of skills and asks to assign one
    deactivate System

    Employee -> System : Selects the skill
    activate System

        System --> Employee : shows collaborator list and asks to select one
    deactivate System

    Employee -> System : selects one collaborator
    activate System

        System --> Employee : shows all data and requests confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : displays operation success
    deactivate System
@enduml