@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


participant "skillrepository\n:SkillRepository" as SR
participant "skill\n:Skill" as HABILIDADE


    group Create Skill
            -> SR: createSkill(skillname)
            activate SR

                SR -> HABILIDADE**: createSkill(skillname)

                SR -> SR: validateSkill(skill)

                SR -> SR: addSkill(skill)


                <-- SR : skill

            deactivate SR


@enduml