@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative Two

autonumber

actor "Human Resources Manager" as HRM
participant ":System" as System

activate HRM

    HRM -> System : asks to register skills that may be appointed to a collaborator
    activate System

    System --> HRM : shows list of collaborators and asks to select one or more
    deactivate System

    HRM -> System : selects collaborator(s)
    activate System

    System --> HRM : shows list of skills and asks to select one or more
    deactivate System

    HRM -> System : selects skill(s)
    activate System

    System --> HRM : shows all data and requests confirmation
    deactivate System

    HRM -> System : confirms data
    activate System

    System --> HRM : displays operation success
    deactivate System

@enduml