@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class HRM {
    name
    vatNumber
    phoneNumber
    email
}

class System {
}

class Team {
    collaborators
    skill list
}

'class User {
'    name
'    email
'    password
'}

HRM "1" - "1" System : provides team size and skills to >
System "1" --- "1" Team: creates >
Team "1" - "1" HRM : is accepted or refused by >
@enduml