@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Green Spaces Manager" as GSM
participant ":System" as System

activate GSM

    GSM -> System : asks to add an entry to the Agenda
    activate System

        System --> GSM : shows list of entries in the To-Do List and asks to select one
    deactivate System

    GSM -> System : selects entry
    activate System

        System --> GSM : asks to select current status and type the starting date
        deactivate System

        GSM -> System : selects status and types starting date
        activate System

    System --> GSM : shows data and requests confirmation
    deactivate System

    GSM -> System : confirms
    activate System

    System --> GSM : displays operation success
    deactivate System

@enduml