@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Organization\nEmployee" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to assign skills to a collaborator
    activate System

    System --> Employee : shows list of skills and asks to select one or more
    deactivate System

    Employee -> System : selects skill(s)
    activate System

    System --> Employee : shows list of collaborators and asks to select one or more
    deactivate System

    Employee -> System : selects collaborator(s)
    activate System

    System --> Employee : shows all data and requests confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

    System --> Employee : displays operation success
    deactivate System

@enduml