@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class GSM {
    name
    vatNumber
    phoneNumber
    email
}

class Entry {
    title/description
    degree of urgency
    approx. duration
}

class ToDoList {
    entries
}

'class User {
'    name
'    email
'    password
'}

GSM "1" - "*" Entry: adds >
GSM "1" -- "1" ToDoList: uses >
Entry "1" -- "1" ToDoList: is shown in >

@enduml