@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Human Resource Manager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to generate a team
    activate System

        System --> Employee : requests data (max. and min. team size and suggested skills)
    deactivate System

    Employee -> System : types requested data
    activate System

        System --> Employee : generates team
    deactivate System

    Employee -> System : either accepts or refuses the team.
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml