@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Collaborator" as ADM
participant ":ConsultTasksUI" as UI
participant ":ConsultTasksController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "collaboratorrepository\n:CollaboratorRepository" as CR
participant "taskRepository:\nTaskRepository" as TAR
participant "teamRepository:\nTeamRepository" as TER
participant "taskList" as TL
participant "ListMapper" as LM
participant "taskListDTO" as TLDTO
participant "taskDTO" as TDTO


activate ADM

        ADM -> UI : asks to consult the tasks assigned to them between two dates.

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create
            activate CTRL

                                  CTRL -> RepositorySingleton : getInstance()
                                                    activate RepositorySingleton

                                                        RepositorySingleton --> CTRL: repositories
                                                    deactivate RepositorySingleton

                                                     CTRL -> CTRL : getCollaboratorFromSession()
                                                     activate CTRL

                                                     ref over CTRL
                                                     Get Collaborator
                                                     end

                                                         CTRL --> CTRL : collaborator
                                                     deactivate CTRL

                                                     CTRL --> UI : collaborator
                                                     deactivate CTRL

            UI -> CTRL : getTeamRepository()
            activate CTRL

                CTRL -> PLAT : getTeamRepository()
                activate PLAT

           PLAT --> CTRL : teamRepository
           deactivate PLAT

           CTRL --> UI : teamRepository
           deactivate CTRL

                       UI -> CTRL : getTaskRepository()
                       activate CTRL

                           CTRL -> PLAT : getTaskRepository()
                           activate PLAT

                      PLAT --> CTRL : taskRepository
                      deactivate PLAT

                      CTRL --> UI : taskRepository
                      deactivate CTRL

                    UI -> CTRL : getTeamByCollaborator(collaborator)
                    activate CTRL

                        CTRL -> TER : getTeamByCollaborator(collaborator)
                        activate TER

                   TER --> CTRL : team
                   deactivate TER

                   CTRL --> UI : team
                   deactivate CTRL
            UI -> CTRL: getTaskByTeam(Team team)
            activate CTRL

            loop for each task
                CTRL -> TAR : getTaskByTeam(Team team)
                activate TAR
            end


            TAR -> TL**: create()


           TAR -> TAR: filterTasksByStatus(taskList)
           activate TAR

           TAR --> TAR: collaboratorTasks
           deactivate TAR

            TAR --> CTRL: collaboratorTasks
            deactivate TAR

            CTRL -> LM: toDTO(collaboratorTasks)
            activate LM

            LM -> TLDTO**: create()

            loop for each task in collaboratorTasks

            LM -> TL: get()

            LM -> LM: toDTO(task)
            activate LM

            LM --> TDTO**: create(task)
            deactivate LM

            LM -> TLDTO: add(taskDTO)
            end

                            LM --> CTRL : taskListDTO

                        deactivate LM

                        CTRL --> UI : taskListDTO
                        deactivate CTRL
        UI --> ADM: shows list of tasks the collaborator is assigned to and asks to select one
        deactivate UI

        ADM -> UI: selects task
        activate UI

        UI -> TL: get(selectedindex)
        activate TL

        TL --> UI: selectedTask

                UI --> ADM: asks for confirmation
                deactivate UI

                ADM -> UI: confirms
                activate UI






        UI -> CTRL : markTaskAsDone(selectedTask)
        activate CTRL

        CTRL -> TAR : markTaskAsDone(selectedTask)
        activate TAR


            UI --> ADM: displays operation success
            deactivate CTRL
            deactivate TAR
    deactivate UI

deactivate ADM

@enduml