@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



participant "Agenda" as AG

    group Postpone Entry

            -> AG: postponeEntry(agendaEntry, date)
                        activate AG

                            AG -> AG: postponeEntry(agendaEntry, date)
                                        activate AG

                                        AG --> AG: true
                                        deactivate AG



@enduml