@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false

skinparam rectangle{
    BorderColor yellow
}

'title Use Case Diagram Example

left to right direction

rectangle "System Actors" as actors {
    actor Freelancer
    actor "Human Resources Manager" as HRM
    actor "Vehicle Fleet Manager" as VFM
    actor "Green Space Manager" as GSM
    actor "Software Quality Assessment Team Manage" as QAM
}


note right of Freelancer
    Actor identified but still
    no concrete use cases
end note

rectangle "Use Cases" as usecases{
    usecase "UC1 - Create a Skill" as UC1
    usecase "UC2 - Create a Job" as UC2
    usecase "UC3 - Register a Collaborator" as UC3
    usecase "UC4 - Assign a Skill" as UC4
    usecase "UC5 - Generate a Team" as UC5
    usecase "UC6 - Register a Vehicle" as UC6
    usecase "UC7 - Register a Vehicle's Maintenance" as UC7
    usecase "UC8 - List Vehicles that need Maintenance" as UC8
    usecase "UC9 - Water Consumption Statistics" as UC9
    usecase "UC10 - Users' Preferences in Equipment" as UC10
    usecase "UC11 - Different Age Groups' Usage of the Park" as UC11
    usecase "UC12 - Import File with Pipe Routes" as UC12
    usecase "UC13 - Apply an Algorithm" as UC13
    usecase "UC14 - Run Tests for Inputs" as UC14

    HRM --> UC1
    HRM --> UC2
    HRM --> UC3
    HRM --> UC4
    HRM --> UC5
    VFM --> UC6
    VFM --> UC7
    VFM --> UC8
    GSM --> UC9
    GSM --> UC10
    GSM --> UC11
    GSM --> UC12
    GSM --> UC13
    QAM --> UC14


}
note right of actors
    Rectangles and Titles are for
    demonstration purposes only.
    Omitt on your diagrams.

end note

@enduml