@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false

skinparam rectangle{
    BorderColor yellow
}

'title Use Case Diagram Example

left to right direction

rectangle "System Actors" as actors {
    actor "Human Resources Manager" as HRM
    actor "Vehicle Fleet Manager" as VFM
    actor "Green Space Manager" as GSM
    actor "Software Quality Assessment Team Manage" as QAM
    actor "Collaborator" as Collaborator
}

rectangle "Use Cases" as usecases {
    usecase "UC1 - Create a Skill" as UC1
    usecase "UC2 - Create a Job" as UC2
    usecase "UC3 - Register a Collaborator" as UC3
    usecase "UC4 - Assign a Skill" as UC4
    usecase "UC5 - Generate a Team" as UC5
    usecase "UC6 - Register a Vehicle" as UC6
    usecase "UC7 - Register a Vehicle's Maintenance" as UC7
    usecase "UC8 - List Vehicles that need Maintenance" as UC8
    usecase "UC9 - Water Consumption Statistics" as UC9
    usecase "UC10 - Users' Preferences in Equipment" as UC10
    usecase "UC11 - Different Age Groups' Usage of the Park" as UC11
    usecase "UC12 - Import File with Pipe Routes" as UC12
    usecase "UC13 - Apply an Algorithm" as UC13
    usecase "UC14 - Run Tests for Inputs" as UC14
    usecase "UC15 - Predict Water Consumption Costs" as UC15
    usecase "UC16 - Polynomial Regression Analysis" as UC16
    usecase "UC17 - Shortest Route to Single Assembly Point" as UC17
    usecase "UC18 - Shortest Route to Multiple Assembly Points" as UC18
    usecase "UC19 - Analyze Worst-case Time Complexity" as UC19
    usecase "UC20 - Register a Green Space" as UC20
    usecase "UC21 - Add Task to To-Do List" as UC21
    usecase "UC22 - Add Task to Agenda" as UC22
    usecase "UC23 - Assign Team to Task" as UC23
    usecase "UC24 - Postpone Task in Agenda" as UC24
    usecase "UC25 - Cancel Task in Agenda" as UC25
    usecase "UC26 - Assign Vehicles to Task" as UC26
    usecase "UC27 - List Managed Green Spaces" as UC27
    usecase "UC28 - Consult Assigned Tasks" as UC28
    usecase "UC29 - Record Task Completion" as UC29

    HRM --> UC1
    HRM --> UC2
    HRM --> UC3
    HRM --> UC4
    HRM --> UC5
    VFM --> UC6
    VFM --> UC7
    VFM --> UC8
    GSM --> UC9
    GSM --> UC10
    GSM --> UC11
    GSM --> UC12
    GSM --> UC13
    QAM --> UC14
    GSM --> UC15
    GSM --> UC16
    GSM --> UC17
    GSM --> UC18
    QAM --> UC19
    GSM --> UC20
    GSM --> UC21
    GSM --> UC22
    GSM --> UC23
    GSM --> UC24
    GSM --> UC25
    GSM --> UC26
    GSM --> UC27
    Collaborator --> UC28
    Collaborator --> UC29

}

@enduml