@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class Collaborator {
    - name: String
    - birthdate: String
    - admission date: String
    - address: String
    - mobile Contact: int
    - email contact: String
    - ID doc type: String
    - ID number: int
}

class CollaboratorManager {
    + registerCollaborator(name: String, \nbirthdate: String, \nadmission date: String, \naddress: String, \nmobile Contact: int, \nemail contact: String, \nID doc type: String, \nID number: int): boolean
}

class HRManager {
    + manageCollaborators(): void
}

CollaboratorManager --> Collaborator: Manages
HRManager --> CollaboratorManager: Uses


Repositories -> Repositories : instance
ApplicationSession -> ApplicationSession : instance

RegisterCollaboratorUI .> RegisterCollaboratorController

RegisterCollaboratorController .> Repositories : repositories

Repositories --> "1" OrganizationRepository

OrganizationRepository --> "*" Organization
ApplicationSession --> "1" UserSession : userSession

RegisterCollaboratorController ..> "1" Organization : organization
RegisterCollaboratorController ..> ApplicationSession
RegisterCollaboratorController ..> UserSession
Collaborator --> HRManager : registered by

Organization --> "*" HRManager : employs
Organization --> "*" Collaborator : employs

@enduml