@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":RegisterCollaboratorController" as CTRL
participant "organization\n:Organization" as ORG

autonumber 16
-> CTRL: assignjob(collaborator, jobname)

autonumber 16.1
activate ORG

    group Assign Job
    activate CTRL

           CTRL -> ORG: getJob(jobname)
             activate ORG


                CTRL -> ORG: giveJob(collaborator, job)


                        ORG --> CTRL : collaborator

                    deactivate ORG

                    <-- CTRL
                    deactivate CTRL

deactivate ORG


@enduml