@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
participant ":collaboratorRepository\n:CollaboratorRepository" as CR
participant "team\n:Team" as EQUIPA



            -> CR: generateTeam(int maxTeamSize, int minTeamSize, List<Skill> requiredSkills)
                        activate CR

                            CR -> CR: filterCollaboratorsBySkills(List<Collaborator> collaborators, List<Skill> requiredSkills)
                            activate CR

                            CR --> CR: qualifiedcollaborators
                            deactivate CR

                            CR -> EQUIPA**: create

                            CR -> EQUIPA: add(qualifiedCollaborators.get(i));

                        <-- CR : team
                        deactivate CR
@enduml