@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
participant ":SkillRepository" as SR


activate SR
-> SR : parseSkills(String inputSkills)
    <-- SR : requiredskills

@enduml