@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Spaces Manager" as ADM
participant ":AssignTeamUI" as UI
participant ":AssignTeamController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "agendaRepository\n:AgendaRepository" as AR
participant "teamRepository\n:TeamRepository" as TR
participant "Agenda" as AG
participant "AgendaEntry" as ENTRADA

activate ADM

        ADM -> UI : asks to assign a team to an entry in the Agenda

        activate UI

'            UI --> ADM : requests data (name)
            'create CTRL
            UI -> CTRL** : create

            activate CTRL

                        CTRL -> RepositorySingleton : getInstance()
                                        activate RepositorySingleton

                                            RepositorySingleton --> CTRL: repositories
                                        deactivate RepositorySingleton

                                         CTRL -> CTRL : getGSMFromSession()
                                         activate CTRL

                                         ref over CTRL
                                         Get GSM
                                         end

                                             CTRL --> CTRL : gsm
                                         deactivate CTRL

                             CTRL -> PLAT : getTeamRepository()
                                     activate PLAT

                                 PLAT -> CTRL : TeamRepository
                                 deactivate PLAT

                             CTRL -> PLAT : getAgendaRepository()
                                     activate PLAT

                                 PLAT -> CTRL : AgendaRepository
                                 deactivate PLAT

                             UI -> CTRL: getAgendaByGSM(gsm)

                             CTRL -> AR: getAgendaByGSM(gsm)
                                         activate AR

                                         AR --> CTRL: agenda
                                         deactivate AR
                             CTRL --> UI : agenda


                             UI -> CTRL : getAgendaEntries()

                            ref over CTRL
                            Get Agenda Entries
                            end

                            CTRL --> UI : agendaEntries
                            deactivate CTRL




    UI --> ADM : shows list of entries and asks to select one
    deactivate UI



    ADM -> UI : selects entry
    activate UI

                                     UI -> AG : get(selectedIndex)
                                     activate AG

                                    AG --> UI : agendaEntry
                                    deactivate AG


                                 UI -> CTRL : getTeamList()
                                 activate CTRL

                                CTRL -> TR : getTeamList()
                                activate TR

                                TR --> CTRL : teams
                                deactivate TR

                                CTRL --> UI : teams
                                deactivate CTRL

    UI --> ADM : shows list of teams and asks to select one
    deactivate UI

        ADM -> UI : selects team
        activate UI

                                             UI -> TR : get(selectedIndex)
                                             activate TR

                                            TR --> UI : team
                                            deactivate TR
        
            UI --> ADM : shows data and requests confirmation
            deactivate UI
        
            ADM -> UI : confirms data
            activate UI


        UI -> CTRL : assignTeam(agendaEntry, team)
        activate CTRL

            |||

            CTRL -> ENTRADA: assignTeam(agendaEntry, team)
            activate ENTRADA

                ENTRADA -> ENTRADA: validateTeam(Team team)
                            activate ENTRADA

                            ENTRADA --> ENTRADA: true
                            deactivate ENTRADA

                ENTRADA -> ENTRADA: addTeam(team)
                activate ENTRADA
                ENTRADA --> ENTRADA: true
                deactivate ENTRADA

                deactivate CTRL

            UI --> ADM: displays operation success
            UI --> ADM: sends message to team members
    deactivate UI

deactivate ADM

@enduml