@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Green Spaces Manager" as GSM
participant ":System" as System

activate GSM

    GSM -> System : asks to assign vehicles to an entry in the Agenda
    activate System

        System --> GSM : shows list of entries and asks to select one
    deactivate System

    GSM -> System : selects entry
    activate System

    System --> GSM : shows list of vehicles and asks to select one or more
    deactivate System

    GSM -> System : selects vehicle(s)
    activate System

    System --> GSM : shows data and requests confirmation
    deactivate System

    GSM -> System : confirms data
    activate System

    System --> GSM : displays operation success

@enduml