@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


participant "ToDoList" as TDL
participant "TDLEntry" as ENTRADA


    group Add Entry

            -> TDL: addEntry(entryTitle, entryDescription, entryUrgency, entryDuration, gsm)
            activate TDL

                TDL -> ENTRADA**: create

                TDL -> TDL: validateEntry(TDLEntry entry)
                activate TDL

                TDL --> TDL: true
                deactivate TDL

                TDL -> TDL: addEntry(TDLEntry entry)
                                activate TDL

                                TDL --> TDL: true
                                deactivate TDL



@enduml