@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



participant ":AddEntryToDoListController" as CTRL
participant "greenSpaceRepository:\nGreenSpaceRepository" as GSR
participant "ListMapper" as LM
participant "greenSpaces" as GS
participant "greenSpacesDTO" as GSDTO
participant "greenSpaceDTO" as GDTO

        -> CTRL : getGreenSpaceList()
                  activate CTRL
    group Get Green Space List



                       CTRL -> GSR : getGreenSpaceList()
                       activate GSR
                    

                     GSR -> GS**: create()

                     GSR --> CTRL: greenSpaces
                     deactivate GSR

                     CTRL -> LM: toDTO(greenSpaces)
                     activate LM

                     LM -> GSDTO**: create()

                     loop for each greenSpace in greenSpaces

                     LM -> GS: get(i)

                     LM -> LM: greenSpaceDTO = toDTO(greenSpace)
                     activate LM

                     LM --> GDTO**: create(greenSpace)
                     deactivate LM

                     LM -> GSDTO: add(greenSpace)
                     end



                     |||

                         LM --> CTRL : getGreenSpaceListDTO
                         deactivate LM


    end

    <-- CTRL : greenSpaceListDTO
deactivate CTRL


@enduml