@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam classAttributeIconSize 0
hide circle
hide methods

'class Platform {
'  -description
'}

class Organization {
    name
    vatNumber
    website
    phoneNumber
    email
}

class Collaborator {
    name
    birthdate
    admission date
    address
    contact info (mobile and email)
    ID doc type and number
}

class HRM {
    name
    email
    position
    phone
}

class VFM {
    name
    email
    position
    phone
}

class Skill{
    name
}

class Job{
    name
}

class Team {
    collaborators
    skill list
}

'class User {
'    name
'    email
'    password
'}

class Vehicle{
    brand
    model
    type
    tare
    gross weight
    current KM
    register date
    acquisition date
    maintenance/check-up frequency
}

class MaintenanceCheckup {
    date
}

class List {
    vehicles that need maintenance
}

Organization "1" -- "*" HRM : has >
Organization "1" --- "*" VFM : has >
Organization "1" --left "*" Collaborator: has >
HRM "1" - "*" Collaborator: registers >
HRM "1" -- "*" Skill: creates >
HRM "1" -- "*" Job: creates >
Collaborator "1" -left "*" Job: is assigned to <
Collaborator "1" -- "*" Skill: is assigned to <
HRM "1" -left "1" System: provides team size and skills to >
System "1" - "1" Team: generates >
HRM "1" -- "1" Team: \nis accepted or refused by <
VFM "1" - "*" Vehicle : registers >
VFM "1" -- "*" MaintenanceCheckup : registers >
Vehicle "1" - "*" MaintenanceCheckup : belongs to <
VFM "1" -- "*" List : requests creation of >

Organization "1" -left "1" PostalAddress : located At >

@enduml