@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class ApplicationSession
{
    + static getInstance()
    + getCurrentSession()
}

class UserSession
{
    + getUserEmail()
}

class GreenSpace {
    - name: String
    - type: String
    - area: double
    + GreenSpace(String name, String type, double area)
    + void validateGreenSpaceName(String name)
    + void validateGreenSpaceType(String type)
    + void validateGreenSpaceArea(double area)
    + boolean equals(Object o)
    + int hashCode()
    + GreenSpace clone()
    + boolean isOfName(String name)
}

class GreenSpaceRepository {
  - List<GreenSpace> greenSpaces
  + Optional<GreenSpace> registerGreenSpace(String name, String type, double area, GSM gsm)
  + boolean addGreenSpace(GreenSpace greenSpace)
  + boolean validateGreenSpace(GreenSpace greenSpace)
  + List<GreenSpace> getGreenSpaceList()
}

class Repositories {
  + getInstance() : Repositories
  + getGreenSpaceRepository() : GreenSpaceRepository
}

class RegisterGSUI {
  - controller: RegisterGSController
  - greenSpaceName: String
  - greenSpaceType: String
  - greenSpaceArea: double
  + RegisterGSController getController()
  + void run()
  + void submitData()
  + void requestData()
  + String requestGSType()
  + String requestGSName()
  + double requestGSArea()
}

class RegisterGSController {
  - greenSpaceRepository: GreenSpaceRepository
  - authenticationRepository: AuthenticationRepository
  + RegisterGSController(GreenSpaceRepository greenSpaceRepository, AuthenticationRepository authenticationRepository)
  + GreenSpaceRepository getGreenSpaceRepository()
  + AuthenticationRepository getAuthenticationRepository()
  + Optional<GreenSpace> registerGreenSpace(String name, String type, double area, GSM gsm)
  + GSM getGSMFromSession()
}

note right of RegisterGSController
  - Green Space data is read from GSM's input
  - Updates the Green Space Repository
end note

note left of RegisterGSUI
  - UI for GSM to input green space data
  - Communicates with RegisterGSController
  - Receives repositories from RegisterGSController
end note

Repositories -> Repositories : instance
ApplicationSession -> ApplicationSession : instance

RegisterGSUI .> RegisterGSController

RegisterGSController -down-> Repositories : retrieves instances

Repositories -down-> GreenSpaceRepository : accesses

RegisterGSController ..> GreenSpaceRepository : greenSpaceRepository

ApplicationSession --> "1" UserSession : userSession

RegisterGSController ..> ApplicationSession
RegisterGSController ..> UserSession

GreenSpaceRepository --> GreenSpace: stores


@enduml