@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


participant "GreenSpaceRepository" as GSR
participant "GreenSpace" as HABILIDADE


    group Register Green Space

                    -> GSR: registerGreenSpace(String name, String type, double area, GSM gsm)
                    activate GSR

                        GSR -> HABILIDADE**: create
                                GSR -> GSR: validateGreenSpace(GreenSpace greenSpace)
                                activate GSR

                                GSR --> GSR: true
                                deactivate GSR

                GSR -> GSR: addGreenSpace(GreenSpace greenSpace)
                                activate GSR

                                GSR --> GSR: true
                                deactivate GSR




                        <-- GSR  : greenSpace

                    deactivate GSR



@enduml