@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Spaces Manager" as ADM
participant ":RegisterGSUI" as UI
participant ":RegisterGSController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "greenSpaceRepository\n:GreenSpaceRepository" as GSR
participant "GreenSpace" as HABILIDADE

activate ADM

        ADM -> UI : asks to register a green space (garden, medium-sized park or large-sized park) and its respective area.

        activate UI

'            UI --> ADM : requests data (name)
            'create CTRL
            UI -> CTRL** : create

            activate CTRL

                        CTRL -> RepositorySingleton : getInstance()
                                        activate RepositorySingleton

                                            RepositorySingleton --> CTRL: repositories
                                        deactivate RepositorySingleton

                             CTRL -> PLAT : getGreenSpaceRepository()
                                     activate PLAT

                                 PLAT --> CTRL : GreenSpaceRepository
                                 deactivate PLAT
                                 CTRL --> UI : GreenSpaceRepository
                                 deactivate CTRL


    UI --> ADM : shows possible types of green spaces and asks to select one
    deactivate UI

        ADM -> UI : selects type
        activate UI
        
            UI --> ADM : requests name and area of the green space
            deactivate UI
        
            ADM -> UI : types name and area
            activate UI
        
            UI --> ADM : shows data and requests confirmation
            deactivate UI
        
            ADM -> UI : confirms data
            activate UI



        UI -> CTRL : registerGreenSpace(String name, String type, double area, GSM gsm)
        activate CTRL

            |||
            CTRL -> CTRL : getGSMFromSession()
            activate CTRL

            ref over CTRL
            Get GSM
            end

                CTRL --> CTRL : gsm
            deactivate CTRL

            |||
            CTRL -> GSR: registerGreenSpace(String name, String type, double area, GSM gsm)
            activate GSR

                GSR -> HABILIDADE**: create

                GSR -> GSR: validateGreenSpace(GreenSpace greenSpace)
                activate GSR

                GSR --> GSR: true
                deactivate GSR

                GSR -> GSR: addGreenSpace(GreenSpace greenSpace)
                                activate GSR

                                GSR --> GSR: true
                                deactivate GSR


                GSR --> CTRL : greenSpace

            deactivate GSR

            CTRL --> UI: greenSpace
            deactivate CTRL
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml