@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "organization\n:Organization" as ORG
participant "skill\n:Skill" as TAREFA
participant "skillrepository\n:SkillRepository" as SR

-> ORG: createSkill(skillname)

activate ORG
    group Create Skill

        ORG -> TAREFA**: createSkill(skillname)
        ORG -> ORG: validateSkill(skill)
        ORG -> SR: addSkill (skill)




    end

    <-- ORG : skill
deactivate ORG


@enduml