@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class HRM {
    name
    vatNumber
    phoneNumber
    email
}

class Job {
    name
}

class Collaborator {
    name
    birthdate
    admission date
    address
    contact info (mobile and email)
    taxpayer number
    ID doc type and number
}

class CollaboratorRepository {
    collaborators
}


HRM "1" - "*" Collaborator : wants to register >
Collaborator "1" --down "*" CollaboratorRepository : saved in >
Collaborator "1" - "1..*" Job : has >
@enduml