@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "organization\n:Organization" as ORG
participant "maintenanceDate\n:MaintenanceDate" as DATE
autonumber 8
-> ORG: createMaintenanceDate(plateNumber, \ncurrent KMs and date of maintenance)

autonumber 8.1
activate ORG
    group Create Maintenance Date

        ORG -> DATE**: createMaintenanceDate(Vehicle, \ncurrent KMs and date of maintenance)
        ORG -> ORG: addMaintenanceDate(maintenanceDate)


                        activate ORG
                            ORG -> ORG: validateMaintenanceDate(maintenanceDate)
                            deactivate ORG


    end

    autonumber 9
    <-- ORG : maintenanceDate
deactivate ORG


@enduml