
@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Vehicle and Equipment\nFleet Manager" as VEFL
participant ":MaintenanceRegisterUI" as UI
participant ":RegisterMaintenanceController" as RMC
participant "organization\n:Organization" as ORG

activate VEFL

        VEFL -> UI : asks to register a vehicle's maintenance date

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> RMC** : create



            UI --> VEFL : requests data (plate ID, current KMs \nand date of maintenance)
        deactivate UI

    VEFL -> UI : types requested data
    activate UI

        UI --> VEFL : shows all data and requests confirmation
    deactivate UI

    VEFL -> UI : confirms data
    activate UI

        UI -> RMC : registerMaintenanceController(plate ID, current KMs \nand date of maintenance)
        activate RMC

            RMC -> RMC : getVehicleByDescription(plate ID, brand, model, type)
            activate RMC
                     ref over RMC
                        Get Vehicle

                     end

               RMC-->RMC : vehicle
            deactivate RMC


             RMC -> RMC : getVFMFromSession()
                        activate RMC
            
                            ref over RMC
                              Get VFM
            
                            end ref
            
                            RMC --> RMC : VFM
                        deactivate RVC
            |||
            RMC -> ORG: createMaintenanceDate(plate ID, current KMs \nand date of maintenance)
            activate ORG

               activate ORG

                               ref over ORG
                                   Create Maintenance Date

                               end

                               ORG --> RMC : maintenanceDate
               deactivate ORG


            deactivate ORG

            RMC --> UI: maintenanceDate
            deactivate RMC
            UI --> VEFL: displays operation success
    deactivate UI

deactivate VEFL

@enduml