@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



'hide footbox
participant ":RegisterMaintenanceController" as RMC
participant "repositories\n:Repositories" as PLAT
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSAO
participant "organizationRepository:\nOrganizationRepository" as OrganizationRepository
participant "organization\n:Organization" as ORG
autonumber 10
-> RMC : getVFMFromSession()
autonumber 10.1
 activate RMC

    group Get VFM

        RMC -> _APP: getInstance()
        activate _APP
           _APP -> RMC: appSession
        deactivate _APP


        RMC -> APP: getCurrentSession()
        activate APP

           APP --> RMC: currentSession
        deactivate APP

        RMC -> SESSAO: email = getUserEmail()
         activate SESSAO

            SESSAO --> RMC: email
         deactivate SESSAO


         RMC -> PLAT: getOrganizationRepository(email)
          activate PLAT

             PLAT --> RMC: organizationRepository
          deactivate PLAT


          RMC -> OrganizationRepository: getOrganizationByVFMEmail(email)
          activate OrganizationRepository

              loop [for each organization
                  OrganizationRepository -> ORG : anyVFMHasEmail(email)
                  activate ORG

                      ORG --> OrganizationRepository : true/false
                  deactivate ORG
              end
          OrganizationRepository --> RMC : organization
          deactivate OrganizationRepository

          RMC -> ORG: getVFMByEmail(email)
          activate ORG

             ORG --> RMC : VFM
          deactivate ORG
    end
    autonumber 11
    <-- RMC : VFM
 deactivate RMC

@enduml