@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Green Spaces Manager" as GSM
participant ":System" as System

activate GSM

    GSM -> System : asks to assign a team to an entry in the Agenda
    activate System

        System --> GSM : shows list of entries and asks to select one
    deactivate System

    GSM -> System : selects entry
    activate System

    System --> GSM : shows list of teams and asks to select one
    deactivate System

    GSM -> System : selects team
    activate System

    System --> GSM : shows data and requests confirmation
    deactivate System

    GSM -> System : confirms data
    activate System

    System --> GSM : displays operation success


    System --> GSM : sends message to team members
    deactivate System

@enduml