@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Vehicle and Equipment\nFleet Manager" as VFM
participant ":System" as System

activate VFM

    VFM -> System : asks to register a vehicle's maintenance date.
    activate System

            System --> VFM : shows list of vehicles (by plate number) and asks to select one
        deactivate System

        VFM -> System : selects vehicle
        activate System

        System --> VFM : requests data (current KMs and date of maintenance)
    deactivate System

    VFM -> System : types requested data
    activate System

    System --> VFM : shows all data and requests confirmation
    deactivate System

    VFM -> System : confirms data
    activate System

        System --> VFM : displays operation success
    deactivate System

@enduml