@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources Manager" as ADM
participant ":CreateSkillUI" as UI
participant ":CreateSkillController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "skillrepository\n:SkillRepository" as SR
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSAO
participant "organizationRepository:\nOrganizationRepository" as OrganizationRepository
participant "organization\n:Organization" as ORG
participant "skill\n:Skill" as HABILIDADE

activate ADM

        ADM -> UI : asks to create a new skill

        activate UI

'            UI --> ADM : requests data (name)
            'create CTRL
            UI -> CTRL** : create

            activate CTRL

                 CTRL -> PLAT : getSkillRepository()
                         activate PLAT

                     PLAT -> CTRL : skillRepository
                     deactivate PLAT
    deactivate CTRL
    UI --> ADM : requests name
    deactivate UI

    ADM -> UI : types requested name
    activate UI

        UI -> CTRL : createSkill(skillname)
        activate CTRL

            |||
            CTRL -> CTRL : getHRMFromSession()
            activate CTRL

                CTRL -> _APP: getInstance()
                activate _APP
                    _APP -> CTRL: appSession
                deactivate _APP


                CTRL -> APP: getCurrentSession()
                activate APP

                    APP --> CTRL: currentSession
                deactivate APP

                CTRL -> SESSAO: email = getUserEmail()
                activate SESSAO

                    SESSAO --> CTRL: email
                deactivate SESSAO


                CTRL -> PLAT: getOrganizationRepository(email)
                activate PLAT

                    PLAT --> CTRL: organizationRepository
                deactivate PLAT


                CTRL -> OrganizationRepository: getOrganizationByHRMEmail(email)
                activate OrganizationRepository

                    loop [for each organization
                        OrganizationRepository -> ORG : anyHRMHasEmail(email)
                        activate ORG

                             ORG --> OrganizationRepository : true/false
                        deactivate ORG
                    end
                    OrganizationRepository --> CTRL : organization
                deactivate OrganizationRepository

                CTRL -> ORG: getHRMByEmail(email)
                activate ORG

                    ORG --> CTRL : hrm
                deactivate ORG

                CTRL --> CTRL : hrm
            deactivate CTRL

            |||
            CTRL -> ORG: createSkill(skillname)
            activate ORG

                ORG -> HABILIDADE**: createSkill(skillname)

                ORG -> ORG: validateSkill(skill)

                ORG -> SR: addSkill(skill)


                ORG --> CTRL : skill

            deactivate ORG

            CTRL --> UI: skill
            deactivate CTRL
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml