@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":AssignSkillUI" as UI
          activate UI
 UI -> UI: add(skills.get(skillIndex).getName().trim())

        UI --> UI: selectedSkillNames



@enduml