@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":AssignSkillController" as CTRL
participant ":collaboratorrepository\n:CollaboratorRepository" as CR
participant "Collaborator" as COLABORADOR

    group Assign Skill
    CTRL -> COLABORADOR: assignSkillsToCollaborator(collaborator.getIDNumber(), skillNames)
    activate COLABORADOR

                                COLABORADOR -> COLABORADOR: addSkill(skill)





                        CTRL --> CR: updateCollaborator(collaborator)
                        deactivate CR



@enduml