@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources Manager" as ADM
participant ":AssignSkillUI" as UI
participant ":AssignSkillController" as CTRL
participant ":Repositories" as RepositorySingleton
participant ":collaboratorrepository\n:CollaboratorRepository" as CR
participant "skillrepository\n:SkillRepository" as SR
participant "repositories\n:Repositories" as PLAT
activate ADM

        ADM -> UI : asks to assign a skill to a collaborator.

        activate UI

'            UI --> ADM : requests data (name)
            'create CTRL
            UI -> CTRL** : create

                         UI -> CTRL : getCollaboratorRepository()
                         activate CTRL

                                 CTRL -> PLAT : getCollaboratorRepository()
                                         activate PLAT

                                     PLAT -> CTRL : collaboratorrepository
                                     deactivate PLAT

                                 CTRL -> PLAT : getSkillRepository()
                                         activate PLAT

                                     PLAT -> CTRL : skillrepository
                                     deactivate PLAT

            UI -> CTRL: getCollaboratorList()
        ref over CTRL
        Get Collaborator List
        end

        CTRL -> UI: collaborators
        deactivate CTRL

    UI --> ADM : shows list of existing collaborators and asks to select one or more
    deactivate UI

    ADM -> UI : selects collaborator(s)
    activate UI

        ref over UI
        Get Selected Collaborator(s)
        end


            UI -> CTRL: getSkillList()
        ref over CTRL
        Get Skill List
        end

        CTRL -> UI: skills
        deactivate CTRL


    UI --> ADM : shows list of existing skills and asks to select one or more
    deactivate UI


   ADM -> UI : selects skill(s)
   activate UI

        ref over UI
        Get Selected Skills
        end



   UI -> ADM : shows selected data and requests confirmation

   ADM -> UI : confirms data

   UI -> CTRL: assignSkillsToCollaborator(selectedCollaborator.getIDNumber(), selectedSkillNames)
   activate CTRL


            |||
            CTRL -> CTRL : getHRMFromSession()
            activate CTRL

            ref over CTRL
            Get HRM
            end

                CTRL --> CTRL : hrm
            deactivate CTRL

            |||
            CTRL -> ORG: assignSkillsToCollaborator(selectedCollaborator.getIDNumber(), selectedSkillNames)
            activate ORG



                    ref over ORG
                    Assign Skill(s)
                    end

                ORG --> CTRL : assignedcollaborator

            deactivate ORG

            CTRL --> UI: assignedcollaborator
            deactivate CTRL
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml