@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":AssignSkillController" as CTRL
participant ":collaboratorrepository\n:CollaboratorRepository" as CR

        -> CTRL: getCollaboratorList()
        activate CTRL

        CTRL -> CR: getCollaboratorList()
        activate CR

        CR -> CTRL: collaborators
        deactivate CR

        <- CTRL: collaborators
        deactivate CTRL


@enduml