@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class GSM {
    name
    vatNumber
    phoneNumber
    email
}

class GreenSpace {
    type
    area
}

'class User {
'    name
'    email
'    password
'}

GSM "1" - "1...*" GreenSpace: registers >

@enduml