@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class Collaborator {
    name
    birthdate
    admission date
    address
    contact info (mobile and email)
    taxpayer number
    ID doc type and number
}

class Task {
    team
    vehicles/equipment
    expected duration
    status
}

class AgendaEntry {
     title
     taskDescription
     urgency
     duration
     associatedGreenSpace
     associatedTeam
     associatedVehicles
     status
     startDate
}

class AgendaRepository {
    agendas
}

class TeamRepository {
    teams
}

class Team {
    collaborators
    teamID
}

class Agenda {
    entries
    gsm
}

'class User {
'    name
'    email
'    password
'}

Team "1" -- "*" Collaborator: consists of >
Team "1" - "1" TeamRepository: stored in >
Collaborator "1" - "*" Task: requests list of >
Task "1" - "1" AgendaEntry: described in >
Team "1" - "*" AgendaEntry: assigned to >
AgendaEntry "1" -- "1" Agenda: shown in >
Agenda "1" -- "1" AgendaRepository: stored in >
@enduml