@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Vehicle and Equipment Fleet Maneger" as ADM
participant ":VehicleResgistrationUI" as UI
participant ":RegisterVehicleController" as RVC
participant ":Repositories" as RepositorySingleton
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehicleRepository\n:VehicleRepository" as VR
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSAO
participant "organizationRepository:\nOrganizationRepository" as OrganizationRepository
participant "organization\n:Organization" as ORG
participant "vehicle\n:Vehicle" as Vehicle

activate ADM

        ADM -> UI : asks to register a vehicle

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> RVC** : create

            UI --> ADM : requests data (Brand, Model, Type, Tare, Gross Weight, Current Km, \nRegister Date, Acquisition Date, Maintenance/Check-up Frequency)
        deactivate UI

    ADM -> UI : types requested data
    activate UI

        UI --> ADM : shows all data and requests confirmation
    deactivate UI

    ADM -> UI : confirmation data
    activate UI

        UI -> RVC : registerVehicle(Brand, Model, Type, Tare, Gross Weight, Current Km, \nRegister Date, Acquisition Date, Maintenance/Check-up Frequency)
        activate RVC


            |||
            RVC -> RVC : getVFMFromSession()
            activate RVC

                RVC -> _APP: getInstance()
                activate _APP
                    _APP -> RVC: appSession
                deactivate _APP


                RVC -> APP: getCurrentSession()
                activate APP

                    APP --> RVC: currentSession
                deactivate APP

                RVC -> SESSAO: email = getUserEmail()
                activate SESSAO

                    SESSAO --> RVC: email
                deactivate SESSAO


                RVC -> PLAT: getOrganizationRepository(email)
                activate PLAT

                    PLAT --> RVC: organizationRepository
                deactivate PLAT


                RVC -> OrganizationRepository: getOrganizationByVFMEmail(email)
                activate OrganizationRepository

                    loop [for each organization
                        OrganizationRepository -> ORG : anyVFMHasEmail(email)
                        activate ORG

                             ORG --> OrganizationRepository : true/false
                        deactivate ORG
                    end
                    OrganizationRepository --> RVC : organization
                deactivate OrganizationRepository

                RVC -> ORG: getVFMByEmail(email)
                activate ORG

                    ORG --> RVC : VFM
                deactivate ORG

                RVC --> RVC : VFM
            deactivate RVC

            |||
            RVC -> ORG: createVehicle(Brand, Model, Type, Tare, Gross Weight, Current Km, \nRegister Date, Acquisition Date, Maintenance/Check-up Frequency, VFM)
            activate ORG

                ORG -> Vehicle**: createVehicle(Brand, Model, Type, Tare, Gross Weight, Current Km, \nRegister Date, Acquisition Date, Maintenance/Check-up Frequency, VFM)
                ORG -> ORG: addVehicle (vehicle)


                activate ORG
                    ORG -> ORG: validateVehicle (vehicle)
                    activate ORG
                        ORG --> ORG
                    deactivate ORG

                    ORG --> ORG
                deactivate ORG

                ORG --> RVC : vehicle

            deactivate ORG

            RVC --> UI: vehicle
            deactivate RVC
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml