@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class GSM {
    name
    vatNumber
    phoneNumber
    email
}

class GreenSpaceRepository {
    GreenSpaces
}

class GreenSpace {
        name
        type
        area
}
GSM "1" -- "*" GreenSpace : requests creation of list of >
GreenSpace "*" - "1" GreenSpaceRepository: stored in >
GreenSpace "*" - "1" GSM: managed by >
@enduml