@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Green Spaces Manager" as GSM
participant ":System" as System

activate GSM

    GSM -> System : asks to register a green space (garden, medium-sized park or large-sized park) and its respective area.
    activate System

        System --> GSM : shows possible types of green spaces and asks to select one
    deactivate System

    GSM -> System : selects type of green space
    activate System

    System --> GSM : requests area of the green space
    deactivate System

    GSM -> System : types area
    activate System

    System --> GSM : shows data and requests confirmation
    deactivate System

    GSM -> System : confirms data
    activate System

    System --> GSM : displays operation success
    deactivate System

@enduml