@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Spaces Manager" as ADM
participant ":CancelEntryUI" as UI
participant ":CancelEntryController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "agendaRepository\n:AgendaRepository" as AR
participant "Agenda" as AG

activate ADM

        ADM -> UI : asks to cancel an entry in the Agenda

        activate UI

'            UI --> ADM : requests data (name)
            'create CTRL
            UI -> CTRL** : create

            activate CTRL

                        CTRL -> RepositorySingleton : getInstance()
                                        activate RepositorySingleton

                                            RepositorySingleton --> CTRL: repositories
                                        deactivate RepositorySingleton

                                         CTRL -> CTRL : getGSMFromSession()
                                         activate CTRL

                                         ref over CTRL
                                         Get GSM
                                         end

                                             CTRL --> CTRL : gsm
                                         deactivate CTRL

                             CTRL -> PLAT : getAgendaRepository()
                                     activate PLAT

                                 PLAT -> CTRL : AgendaRepository
                                 deactivate PLAT

                             UI -> CTRL: getAgendaByGSM(gsm)

                             CTRL -> AR: getAgendaByGSM(gsm)
                                         activate AR

                                         AR --> CTRL: agenda
                                         deactivate AR
                             CTRL --> UI : agenda


                             UI -> CTRL : getAgendaEntries()
                            CTRL -> AG : getAgendaEntries()
                            activate AG

                            AG --> CTRL : agendaEntries
                            deactivate AG

                            CTRL --> UI : agendaEntries
                            deactivate CTRL




    UI --> ADM : shows list of entries and asks to select one
    deactivate UI



    ADM -> UI : selects entry
    activate UI

                                     UI -> AG : get(selectedIndex)
                                     activate AG

                                    AG --> UI : agendaEntry
                                    deactivate AG


            UI --> ADM : shows data and requests confirmation
            deactivate UI

            ADM -> UI : confirms data
            activate UI


        UI -> CTRL : cancelEntry(agendaEntry)
        activate CTRL

            |||

            CTRL -> AG: cancelEntry(agendaEntry)
            activate AG

               ref over AG
               Cancel Entry
               end
                deactivate CTRL

            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml