@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

class HRM {
    name
    vatNumber
    phoneNumber
    email
}

class Job {
    name
}

class JobRepository {
    jobs
}

'class Collaborator {
    'name
    'email
    'password
'}

HRM "1" - "*" Job: creates >
Job "1" - "1" JobRepository : is saved in >
@enduml