@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "collaboratorRepository\n:CollaboratorRepository" as CR
participant "collaborator\n:Collaborator" as COLABORADOR

activate CR
    group Register Collaborator

                    -> CR: registerCollaborator(name, birthdate, admission date, address, \nmobile contact, email contact, taxpayer number, ID doc type, ID number)
                    activate CR

                                CR -> COLABORADOR**: create(name, birthdate, admission date, address, \nmobile contact, email contact, taxpayer number, ID doc type, ID number)

                                CR -> CR : validateCollaborator(collaborator)

                                CR -> CR : collaborator
       deactivate CR
    end




@enduml