@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "organization\n:Organization" as ORG
participant ":collaboratorrepository\n:CollaboratorRepository" as CR
participant "skillrepository\n:SkillRepository" as SR

    group Assign Skill
            -> ORG: assignSkill(collaborator, selectedskills)
            activate ORG



                    ORG -> SR: validateSkill(selectedskills)
                    ORG -> CR: validateCollaborator(collaborator)
                    activate CR
                ORG -> CR: saveChanges (collaborator, selectedskills)
deactivate CR


                <-- ORG : assignedcollaborator



@enduml