@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":AssignSkillUI" as UI
          activate UI
          UI -> UI: get(collaboratorindex)

                 UI --> UI: selectedcollaborators



@enduml