@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "AssignSkillController" as CTRL
participant "skillrepository\n:SkillRepository" as SR

        -> CTRL : getSelectedSkill(name)
        activate CTRL

        CTRL -> SR : getSelectedSkill(name)
        activate SR

        SR -> CTRL : selectedskills
        deactivate SR

        <- CTRL : selectedskills
        deactivate SR


@enduml