@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources Manager" as ADM
participant ":AssignSkillUI" as UI
participant ":AssignSkillController" as CTRL
participant ":Repositories" as RepositorySingleton
participant ":collaboratorrepository\n:CollaboratorRepository" as CR
participant "skillrepository\n:SkillRepository" as SR
participant "repositories\n:Repositories" as PLAT
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSAO
participant "organizationRepository:\nOrganizationRepository" as OrganizationRepository
participant "organization\n:Organization" as ORG

activate ADM

        ADM -> UI : asks to assign a skill to a collaborator.

        activate UI

'            UI --> ADM : requests data (name)
            'create CTRL
            UI -> CTRL** : create

                         UI -> CTRL : getCollaboratorRepository()
                         activate CTRL

                                 CTRL -> PLAT : getCollaboratorRepository()
                                         activate PLAT

                                     PLAT -> CTRL : collaboratorrepository
                                     deactivate PLAT

                                 CTRL -> PLAT : getSkillRepository()
                                         activate PLAT

                                     PLAT -> CTRL : skillrepository
                                     deactivate PLAT

            UI -> CTRL: getCollaboratorList()
        CTRL -> CR: getCollaboratorList()
        activate CR

        CR -> CTRL: collaborators
        deactivate CR

        CTRL -> UI: collaborators
        deactivate CTRL

    UI --> ADM : shows list of existing collaborators and asks to select one or more
    deactivate UI

    ADM -> UI : selects collaborator(s)
    activate UI

        UI -> UI: get(collaboratorindex)

        UI --> UI: selectedcollaborators


            UI -> CTRL: getSkillList()
        CTRL -> SR: getSkillList()
        activate SR

        SR -> CTRL: skills
        deactivate SR

        CTRL -> UI: skills
        deactivate CTRL


    UI --> ADM : shows list of existing skills and asks to select one or more
    deactivate UI


   ADM -> UI : selects skill(s)
   activate UI

        UI -> UI: add(skills.get(skillIndex).getName().trim())

        UI --> UI: selectedSkillNames



   UI -> ADM : shows selected data and requests confirmation

   ADM -> UI : confirms data

   UI -> CTRL: assignSkillsToCollaborator(selectedCollaborator.getIDNumber(), selectedSkillNames)
   activate CTRL


            |||
            CTRL -> CTRL : getHRMFromSession()
            activate CTRL

                CTRL -> _APP: getInstance()
                activate _APP
                    _APP -> CTRL: appSession
                deactivate _APP


                CTRL -> APP: getCurrentSession()
                activate APP

                    APP --> CTRL: currentSession
                deactivate APP

                CTRL -> SESSAO: email = getUserEmail()
                activate SESSAO

                    SESSAO --> CTRL: email
                deactivate SESSAO


                CTRL -> PLAT: getOrganizationRepository(email)
                activate PLAT

                    PLAT --> CTRL: organizationRepository
                deactivate PLAT


                CTRL -> OrganizationRepository: getOrganizationByHRMEmail(email)
                activate OrganizationRepository

                    loop [for each organization
                        OrganizationRepository -> ORG : anyHRMHasEmail(email)
                        activate ORG

                             ORG --> OrganizationRepository : true/false
                        deactivate ORG
                    end
                    OrganizationRepository --> CTRL : organization
                deactivate OrganizationRepository

                CTRL -> ORG: getHRMByEmail(email)
                activate ORG

                    ORG --> CTRL : hrm
                deactivate ORG

                CTRL --> CTRL : hrm
            deactivate CTRL

            |||
            CTRL -> ORG: assignSkillsToCollaborator(selectedCollaborator.getIDNumber(), selectedSkillNames)
            activate ORG



                    ORG -> ORG: validateSkill(selectedSkillNames)
                    ORG -> ORG: validateCollaborator(collaboratorID)
                ORG -> COLABORADOR: addskill(selectedSkillNames)
                ORG -> CR: updateCollaborator(collaborator)


                ORG --> CTRL : assignedcollaborator

            deactivate ORG

            CTRL --> UI: assignedcollaborator
            deactivate CTRL
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml