@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "organization\n:Organization" as ORG

autonumber 16
-> ORG: registerCollaborator(name, birthdate, admission date, address, \nmobile contact, email contact, ID doc type, ID number)

autonumber 16.1
activate ORG
    group Assign Skill

        activate ORG
            ORG -> ORG: validateSkill(skillname)
            ORG -> ORG: validateCollaborator(ID number)
            ORG -> ORG: assignSkill(ID number, skillname)

    end

    autonumber 17
    <-- ORG : assignedcollaborator
deactivate ORG


@enduml