@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "organization\n:Organization" as ORG
participant "collaborator\n:Collaborator" as COLABORADOR

autonumber 16
-> ORG: registerCollaborator(name, birthdate, admission date, address, \nmobile contact, email contact, ID doc type, ID number)

autonumber 16.1
activate ORG
    group Register Collaborator

        ORG -> COLABORADOR**: getCollaborator (ID number)

        activate ORG
            ORG -> ORG: validateCollaborator(collaborator)
            activate ORG
    end

    autonumber 17
    <-- ORG : collaborator
deactivate ORG


@enduml