@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "organization\n:Organization" as ORG
participant "collaborator\n:Collaborator" as COLABORADOR

autonumber 16
-> ORG: getSkill(skillname)

autonumber 16.1
activate ORG
    group Get Skill
        ORG -> ORG: showSkillList()


        ORG -> ORG: validateSkill()

    end

    autonumber 17
    <-- ORG : skill
deactivate ORG


@enduml