@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources Manager" as ADM
participant ":AssignSkillUI" as UI
participant ":AssignSkillController" as CTRL
participant "organization\n:Organization" as ORG

activate ADM

    ADM -> UI : asks to assign a skill to a collaborator

    activate UI

        UI -> CTRL** : create

        activate CTRL

        UI --> ADM : shows list of collaborators and asks to select one or more
    deactivate UI

    ADM -> UI : selects collaborator(s)
    activate UI

        UI -> CTRL : getCollaborator(ID number)


        CTRL -> ORG : getCollaborator(ID number)


        ref over ORG
        Get Collaborator(s)
        end

        ORG -> CTRL : collaborators



        CTRL -> UI : collaborators
        deactivate CTRL

        UI --> ADM : shows list of skills and asks to select one or more
    deactivate UI

    ADM -> UI : selects skill(s)
    activate UI

        UI -> CTRL : getSkill(skillname)
        activate CTRL

        CTRL -> ORG : getSkill(skillname)

        ref over ORG
        Get Skill(s)
        end

        ORG -> CTRL : skills



        CTRL -> UI : skills
        deactivate CTRL


            CTRL -> CTRL : getEmployeeFromSession()
            activate CTRL

                ref over CTRL
                    Get Employee

                end ref
                CTRL -> CTRL : employee


            CTRL -> ORG: assignSkill(collaborators, skills)
            activate ORG

                ref over ORG
                    Assign Skills

                end

                ORG --> CTRL : changedcollaborator
            deactivate ORG

            CTRL --> UI: changedcollaborator
            deactivate CTRL
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml